# Используем официальный образ Python
FROM python:latest

WORKDIR /app
COPY . /app

RUN apt-get update && apt-get install -y libssl-dev

RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt


CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3425"]
